#!/bin/bash

jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install qgrid2

# Remove output from Jupyter notebooks
# jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace examples/python_example_for_Jupyter.ipynb
# jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace examples/R_example_for_Jupyter.ipynb
