#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --sys-prefix --py nbgrader
jupyter serverextension enable --sys-prefix --py nbgrader

# Remove output from Jupyter notebooks
# jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace pyopenms/reading_mzml.ipynb
